// AUTO-GENERATED by scripts/gen-db-types.ts — do not edit by hand. Run `npm run db:types`.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      events: {
        Row: {
          address: string | null;
          id: string;
          invitation_id: string;
          lat: number | null;
          lng: number | null;
          sort: number;
          starts_at: string;
          title_i18n: Json;
          venue_name: string | null;
        };
        Insert: {
          address?: string | null;
          id?: string;
          invitation_id: string;
          lat?: number | null;
          lng?: number | null;
          sort?: number;
          starts_at: string;
          title_i18n?: Json;
          venue_name?: string | null;
        };
        Update: {
          address?: string | null;
          id?: string;
          invitation_id?: string;
          lat?: number | null;
          lng?: number | null;
          sort?: number;
          starts_at?: string;
          title_i18n?: Json;
          venue_name?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "events_invitation_id_fkey";
            columns: ["invitation_id"];
            isOneToOne: false;
            referencedRelation: "invitations";
            referencedColumns: ["id"];
          },
        ];
      };
      guests: {
        Row: {
          code: string;
          created_at: string;
          group_name: string | null;
          id: string;
          invitation_id: string;
          max_people: number;
          name: string;
          opened_at: string | null;
          phone: string | null;
          sent_at: string | null;
        };
        Insert: {
          code?: string;
          created_at?: string;
          group_name?: string | null;
          id?: string;
          invitation_id: string;
          max_people?: number;
          name: string;
          opened_at?: string | null;
          phone?: string | null;
          sent_at?: string | null;
        };
        Update: {
          code?: string;
          created_at?: string;
          group_name?: string | null;
          id?: string;
          invitation_id?: string;
          max_people?: number;
          name?: string;
          opened_at?: string | null;
          phone?: string | null;
          sent_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "guests_invitation_id_fkey";
            columns: ["invitation_id"];
            isOneToOne: false;
            referencedRelation: "invitations";
            referencedColumns: ["id"];
          },
        ];
      };
      invitations: {
        Row: {
          active_until: string | null;
          created_at: string;
          data: Json;
          id: string;
          locales: string[];
          main_event_date: string | null;
          owner_id: string;
          published_at: string | null;
          slug: string;
          status: Database["public"]["Enums"]["invitation_status"];
          template_id: string;
          updated_at: string;
        };
        Insert: {
          active_until?: string | null;
          created_at?: string;
          data?: Json;
          id?: string;
          locales?: string[];
          main_event_date?: string | null;
          owner_id: string;
          published_at?: string | null;
          slug: string;
          status?: Database["public"]["Enums"]["invitation_status"];
          template_id: string;
          updated_at?: string;
        };
        Update: {
          active_until?: string | null;
          created_at?: string;
          data?: Json;
          id?: string;
          locales?: string[];
          main_event_date?: string | null;
          owner_id?: string;
          published_at?: string | null;
          slug?: string;
          status?: Database["public"]["Enums"]["invitation_status"];
          template_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "invitations_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "invitations_template_id_fkey";
            columns: ["template_id"];
            isOneToOne: false;
            referencedRelation: "templates";
            referencedColumns: ["id"];
          },
        ];
      };
      music_tracks: {
        Row: {
          artist: string | null;
          category: string | null;
          created_at: string;
          duration: number | null;
          id: string;
          is_active: boolean;
          title: string;
          url: string;
        };
        Insert: {
          artist?: string | null;
          category?: string | null;
          created_at?: string;
          duration?: number | null;
          id?: string;
          is_active?: boolean;
          title: string;
          url: string;
        };
        Update: {
          artist?: string | null;
          category?: string | null;
          created_at?: string;
          duration?: number | null;
          id?: string;
          is_active?: boolean;
          title?: string;
          url?: string;
        };
        Relationships: [];
      };
      orders: {
        Row: {
          amount_uzs: number;
          created_at: string;
          id: string;
          invitation_id: string | null;
          paid_at: string | null;
          promo_code_id: string | null;
          provider: Database["public"]["Enums"]["payment_provider"];
          provider_tx_id: string | null;
          status: Database["public"]["Enums"]["order_status"];
          user_id: string;
        };
        Insert: {
          amount_uzs: number;
          created_at?: string;
          id?: string;
          invitation_id?: string | null;
          paid_at?: string | null;
          promo_code_id?: string | null;
          provider: Database["public"]["Enums"]["payment_provider"];
          provider_tx_id?: string | null;
          status?: Database["public"]["Enums"]["order_status"];
          user_id: string;
        };
        Update: {
          amount_uzs?: number;
          created_at?: string;
          id?: string;
          invitation_id?: string | null;
          paid_at?: string | null;
          promo_code_id?: string | null;
          provider?: Database["public"]["Enums"]["payment_provider"];
          provider_tx_id?: string | null;
          status?: Database["public"]["Enums"]["order_status"];
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "orders_invitation_id_fkey";
            columns: ["invitation_id"];
            isOneToOne: false;
            referencedRelation: "invitations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "orders_promo_code_id_fkey";
            columns: ["promo_code_id"];
            isOneToOne: false;
            referencedRelation: "promo_codes";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "orders_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      page_views: {
        Row: {
          guest_id: string | null;
          id: number;
          invitation_id: string;
          user_agent_short: string | null;
          viewed_at: string;
        };
        Insert: {
          guest_id?: string | null;
          id?: never;
          invitation_id: string;
          user_agent_short?: string | null;
          viewed_at?: string;
        };
        Update: {
          guest_id?: string | null;
          id?: never;
          invitation_id?: string;
          user_agent_short?: string | null;
          viewed_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "page_views_guest_id_fkey";
            columns: ["guest_id"];
            isOneToOne: false;
            referencedRelation: "guests";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "page_views_invitation_id_fkey";
            columns: ["invitation_id"];
            isOneToOne: false;
            referencedRelation: "invitations";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          created_at: string;
          full_name: string | null;
          id: string;
          locale: string;
          phone: string | null;
          role: Database["public"]["Enums"]["user_role"];
          telegram_id: number | null;
          telegram_username: string | null;
        };
        Insert: {
          created_at?: string;
          full_name?: string | null;
          id: string;
          locale?: string;
          phone?: string | null;
          role?: Database["public"]["Enums"]["user_role"];
          telegram_id?: number | null;
          telegram_username?: string | null;
        };
        Update: {
          created_at?: string;
          full_name?: string | null;
          id?: string;
          locale?: string;
          phone?: string | null;
          role?: Database["public"]["Enums"]["user_role"];
          telegram_id?: number | null;
          telegram_username?: string | null;
        };
        Relationships: [];
      };
      promo_codes: {
        Row: {
          code: string;
          created_at: string;
          id: string;
          is_active: boolean;
          max_uses: number | null;
          type: Database["public"]["Enums"]["promo_type"];
          used_count: number;
          valid_until: string | null;
          value: number;
        };
        Insert: {
          code: string;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          max_uses?: number | null;
          type: Database["public"]["Enums"]["promo_type"];
          used_count?: number;
          valid_until?: string | null;
          value: number;
        };
        Update: {
          code?: string;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          max_uses?: number | null;
          type?: Database["public"]["Enums"]["promo_type"];
          used_count?: number;
          valid_until?: string | null;
          value?: number;
        };
        Relationships: [];
      };
      reserved_slugs: {
        Row: {
          slug: string;
        };
        Insert: {
          slug: string;
        };
        Update: {
          slug?: string;
        };
        Relationships: [];
      };
      reviews: {
        Row: {
          created_at: string;
          id: string;
          invitation_id: string | null;
          is_published: boolean;
          rating: number;
          text: string | null;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          invitation_id?: string | null;
          is_published?: boolean;
          rating: number;
          text?: string | null;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          invitation_id?: string | null;
          is_published?: boolean;
          rating?: number;
          text?: string | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "reviews_invitation_id_fkey";
            columns: ["invitation_id"];
            isOneToOne: false;
            referencedRelation: "invitations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reviews_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      rsvps: {
        Row: {
          comment: string | null;
          created_at: string;
          event_ids: string[];
          guest_id: string | null;
          id: string;
          invitation_id: string;
          name: string;
          people_count: number;
          status: Database["public"]["Enums"]["rsvp_status"];
        };
        Insert: {
          comment?: string | null;
          created_at?: string;
          event_ids?: string[];
          guest_id?: string | null;
          id?: string;
          invitation_id: string;
          name: string;
          people_count?: number;
          status: Database["public"]["Enums"]["rsvp_status"];
        };
        Update: {
          comment?: string | null;
          created_at?: string;
          event_ids?: string[];
          guest_id?: string | null;
          id?: string;
          invitation_id?: string;
          name?: string;
          people_count?: number;
          status?: Database["public"]["Enums"]["rsvp_status"];
        };
        Relationships: [
          {
            foreignKeyName: "rsvps_guest_id_fkey";
            columns: ["guest_id"];
            isOneToOne: false;
            referencedRelation: "guests";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "rsvps_invitation_id_fkey";
            columns: ["invitation_id"];
            isOneToOne: false;
            referencedRelation: "invitations";
            referencedColumns: ["id"];
          },
        ];
      };
      templates: {
        Row: {
          category: Database["public"]["Enums"]["event_category"];
          created_at: string;
          id: string;
          is_active: boolean;
          is_new: boolean;
          layout: string;
          name_i18n: Json;
          preview_url: string | null;
          price_uzs: number;
          slug: string;
          sort: number;
          tags: string[];
          theme: string;
          tier: Database["public"]["Enums"]["template_tier"];
        };
        Insert: {
          category: Database["public"]["Enums"]["event_category"];
          created_at?: string;
          id?: string;
          is_active?: boolean;
          is_new?: boolean;
          layout: string;
          name_i18n?: Json;
          preview_url?: string | null;
          price_uzs: number;
          slug: string;
          sort?: number;
          tags?: string[];
          theme: string;
          tier?: Database["public"]["Enums"]["template_tier"];
        };
        Update: {
          category?: Database["public"]["Enums"]["event_category"];
          created_at?: string;
          id?: string;
          is_active?: boolean;
          is_new?: boolean;
          layout?: string;
          name_i18n?: Json;
          preview_url?: string | null;
          price_uzs?: number;
          slug?: string;
          sort?: number;
          tags?: string[];
          theme?: string;
          tier?: Database["public"]["Enums"]["template_tier"];
        };
        Relationships: [];
      };
      wishes: {
        Row: {
          author_name: string;
          created_at: string;
          guest_id: string | null;
          id: string;
          invitation_id: string;
          is_visible: boolean;
          message: string;
        };
        Insert: {
          author_name: string;
          created_at?: string;
          guest_id?: string | null;
          id?: string;
          invitation_id: string;
          is_visible?: boolean;
          message: string;
        };
        Update: {
          author_name?: string;
          created_at?: string;
          guest_id?: string | null;
          id?: string;
          invitation_id?: string;
          is_visible?: boolean;
          message?: string;
        };
        Relationships: [
          {
            foreignKeyName: "wishes_guest_id_fkey";
            columns: ["guest_id"];
            isOneToOne: false;
            referencedRelation: "guests";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "wishes_invitation_id_fkey";
            columns: ["invitation_id"];
            isOneToOne: false;
            referencedRelation: "invitations";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      generate_guest_code: { Args: { len?: number }; Returns: string };
      is_admin: { Args: never; Returns: boolean };
      owns_invitation: { Args: { inv_id: string }; Returns: boolean };
    };
    Enums: {
      event_category: "wedding" | "nikoh" | "fotiha" | "osh" | "birthday" | "other";
      invitation_status: "draft" | "pending_payment" | "active" | "expired" | "blocked";
      order_status: "pending" | "paid" | "failed" | "refunded" | "manual";
      payment_provider: "payme" | "click" | "manual";
      promo_type: "percent" | "fixed";
      rsvp_status: "yes" | "no" | "maybe";
      template_tier: "basic" | "premium" | "vip";
      user_role: "customer" | "admin";
    };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T];
