/**
 * Generates src/types/database.ts from supabase/migrations without Docker:
 * applies migrations to an in-memory Postgres (PGlite) and emits types in the
 * same shape as `supabase gen types typescript`.
 *
 * Usage: npm run db:types
 * (Once a Supabase project is linked, `npm run db:types:remote` is equivalent.)
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { createTestDb } from "../tests/db/harness";

type ColumnRow = {
  table_name: string;
  column_name: string;
  udt_name: string;
  data_type: string;
  is_nullable: "YES" | "NO";
  column_default: string | null;
  is_identity: "YES" | "NO";
};

type FkRow = {
  table_name: string;
  constraint_name: string;
  columns: string[];
  ref_table: string;
  ref_columns: string[];
  is_one_to_one: boolean;
};

type FnRow = { name: string; args: string; returns: string };

const SCALARS: Record<string, string> = {
  uuid: "string",
  text: "string",
  varchar: "string",
  citext: "string",
  date: "string",
  timestamptz: "string",
  timestamp: "string",
  bool: "boolean",
  int2: "number",
  int4: "number",
  int8: "number",
  float4: "number",
  float8: "number",
  numeric: "number",
  jsonb: "Json",
  json: "Json",
};

function tsType(udt: string, enums: Set<string>): string {
  if (udt.startsWith("_")) return `${tsType(udt.slice(1), enums)}[]`;
  if (enums.has(udt)) return `Database["public"]["Enums"]["${udt}"]`;
  const scalar = SCALARS[udt];
  if (!scalar) throw new Error(`Unmapped Postgres type: ${udt}`);
  return scalar;
}

async function main() {
  const db = await createTestDb();

  const enumRows = await db.query<{ name: string; labels: string[] }>(`
    select t.typname as name, array_agg(e.enumlabel order by e.enumsortorder) as labels
    from pg_type t join pg_enum e on e.enumtypid = t.oid
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public' group by t.typname order by t.typname`);
  const enums = new Set(enumRows.rows.map((r) => r.name));

  const columns = await db.query<ColumnRow>(`
    select c.table_name, c.column_name, c.udt_name, c.data_type, c.is_nullable, c.column_default, c.is_identity
    from information_schema.columns c
    join information_schema.tables t on t.table_schema = c.table_schema and t.table_name = c.table_name
    where c.table_schema = 'public' and t.table_type = 'BASE TABLE'
    order by c.table_name, c.column_name`);

  const fks = await db.query<FkRow>(`
    select cl.relname as table_name, con.conname as constraint_name,
      array(select a.attname from unnest(con.conkey) k join pg_attribute a on a.attrelid = con.conrelid and a.attnum = k) as columns,
      rcl.relname as ref_table,
      array(select a.attname from unnest(con.confkey) k join pg_attribute a on a.attrelid = con.confrelid and a.attnum = k) as ref_columns,
      exists (
        select 1 from pg_constraint u
        where u.conrelid = con.conrelid and u.contype in ('p', 'u')
          and (select array_agg(x order by x) from unnest(u.conkey) x) = (select array_agg(x order by x) from unnest(con.conkey) x)
      ) as is_one_to_one
    from pg_constraint con
    join pg_class cl on cl.oid = con.conrelid
    join pg_namespace n on n.oid = cl.relnamespace
    join pg_class rcl on rcl.oid = con.confrelid
    join pg_namespace rn on rn.oid = rcl.relnamespace
    where con.contype = 'f' and n.nspname = 'public' and rn.nspname = 'public'
    order by cl.relname, con.conname`);

  const fns = await db.query<FnRow>(`
    select p.proname as name, pg_get_function_arguments(p.oid) as args, format_type(p.prorettype, null) as returns
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and format_type(p.prorettype, null) <> 'trigger'
    order by p.proname`);

  const byTable = new Map<string, ColumnRow[]>();
  for (const col of columns.rows) {
    byTable.set(col.table_name, [...(byTable.get(col.table_name) ?? []), col]);
  }

  const out: string[] = [];
  const line = (s: string) => out.push(s);

  line("// AUTO-GENERATED by scripts/gen-db-types.ts — do not edit by hand. Run `npm run db:types`.");
  line("");
  line("export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];");
  line("");
  line("export type Database = {");
  line("  public: {");
  line("    Tables: {");
  for (const [table, cols] of byTable) {
    line(`      ${table}: {`);
    for (const kind of ["Row", "Insert", "Update"] as const) {
      line(`        ${kind}: {`);
      for (const c of cols) {
        const base = tsType(c.udt_name, enums);
        const nullable = c.is_nullable === "YES";
        const type = nullable ? `${base} | null` : base;
        if (kind === "Row") {
          line(`          ${c.column_name}: ${type};`);
          continue;
        }
        const generatedAlways = c.is_identity === "YES";
        if (generatedAlways) {
          line(`          ${c.column_name}?: never;`);
          continue;
        }
        const optional = kind === "Update" || nullable || c.column_default !== null;
        line(`          ${c.column_name}${optional ? "?" : ""}: ${type};`);
      }
      line("        };");
    }
    const rels = fks.rows.filter((f) => f.table_name === table);
    if (rels.length === 0) {
      line("        Relationships: [];");
    } else {
      line("        Relationships: [");
      for (const r of rels) {
        line("          {");
        line(`            foreignKeyName: "${r.constraint_name}";`);
        line(`            columns: [${r.columns.map((c) => `"${c}"`).join(", ")}];`);
        line(`            isOneToOne: ${r.is_one_to_one};`);
        line(`            referencedRelation: "${r.ref_table}";`);
        line(`            referencedColumns: [${r.ref_columns.map((c) => `"${c}"`).join(", ")}];`);
        line("          },");
      }
      line("        ];");
    }
    line("      };");
  }
  line("    };");
  line("    Views: { [_ in never]: never };");
  line("    Functions: {");
  for (const fn of fns.rows) {
    const args = fn.args
      .split(",")
      .map((a) => a.trim())
      .filter(Boolean)
      .map((a) => {
        const [name, type, ...rest] = a.split(/\s+/);
        const hasDefault = rest.includes("DEFAULT");
        const udt = type === "integer" ? "int4" : type === "uuid" ? "uuid" : "text";
        return `${name}${hasDefault ? "?" : ""}: ${tsType(udt, enums)}`;
      });
    const returns = fn.returns === "boolean" ? "boolean" : fn.returns === "integer" ? "number" : "string";
    line(
      `      ${fn.name}: { Args: ${args.length ? `{ ${args.join("; ")} }` : "never"}; Returns: ${returns} };`,
    );
  }
  line("    };");
  line("    Enums: {");
  for (const e of enumRows.rows) {
    line(`      ${e.name}: ${e.labels.map((l) => `"${l}"`).join(" | ")};`);
  }
  line("    };");
  line("    CompositeTypes: { [_ in never]: never };");
  line("  };");
  line("};");
  line("");
  line('type PublicSchema = Database["public"];');
  line('export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];');
  line(
    'export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];',
  );
  line(
    'export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];',
  );
  line('export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T];');
  line("");

  const target = path.resolve(__dirname, "../src/types/database.ts");
  writeFileSync(target, out.join("\n"));
  await db.close();
  console.log(`Wrote ${path.relative(process.cwd(), target)} (${byTable.size} tables, ${enums.size} enums)`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
